// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etfqlkdrxyhkcjnnqnkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0ZnFsa2RyeHloa2Nqbm5xbmtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDMyNjksImV4cCI6MjA2NTgxOTI2OX0.nnVk2-lFi9GBrhNVXYR12PxOEwHcGHua8n2e5x96m2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);